// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsgc5hdKxWPSXl8GbLxI-4L-WlA5NgUQ',
    appId: '1:136298601240:web:df35c04e428220883d5c6d',
    messagingSenderId: '136298601240',
    projectId: 'farmai-b6357',
    authDomain: 'farmai-b6357.firebaseapp.com',
    storageBucket: 'farmai-b6357.appspot.com',
    measurementId: 'G-MML55G4XBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNOgW1WGc1KOZS2uDwciPaTdggcKp10XQ',
    appId: '1:136298601240:android:9085e58c594a11bc3d5c6d',
    messagingSenderId: '136298601240',
    projectId: 'farmai-b6357',
    storageBucket: 'farmai-b6357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1bu5awz7Y5buXMHdSqDjuMMMMin8I4i8',
    appId: '1:136298601240:ios:a3bbdff8a6cfec173d5c6d',
    messagingSenderId: '136298601240',
    projectId: 'farmai-b6357',
    storageBucket: 'farmai-b6357.appspot.com',
    iosBundleId: 'com.example.farmwiseAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1bu5awz7Y5buXMHdSqDjuMMMMin8I4i8',
    appId: '1:136298601240:ios:49cfbfec9bc9ee1b3d5c6d',
    messagingSenderId: '136298601240',
    projectId: 'farmai-b6357',
    storageBucket: 'farmai-b6357.appspot.com',
    iosBundleId: 'com.example.farmwiseAi.RunnerTests',
  );
}
